name: fall-detection
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip
  - pytorch
  - cuda-toolkit=11.8
  - torchvision
  - pillow
  - matplotlib
  - numpy
  - pandas
  - tqdm
  - wandb
  - ipykernel