model:
  backbone: "convnext_tiny"
  pretrained: true

optimizer:
  lr: 1.0e-4
  weight_decay: 1.0e-2

train:
  epochs: 10
  output_dir: "weights/"
  run_name: "convnext-tiny_ntu-rgb_240p"

dataset:
  root: "/home/archy1/datasets/fall-detection/ntu/processed/"
  modality: "rgb"

transforms:
  image_size: [240, 426]
  

dataloader:
  batch_size: 96
  num_workers: 8

tags:
  - "cnn"
  - "rgb"
  - "ntu"