fusion: "late"

model:
  backbone: "convnext_tiny"
  rgb_weights: "weights/convnext-tiny_ntu-rgb_240p/best.pt"
  depth_weights: "weights/convnext-tiny_ntu-depth_240p/best.pt"

optimizer:
  lr: 1.0e-4
  weight_decay: 1.0e-2

train:
  epochs: 5
  output_dir: "weights/"
  run_name: "convnext-tiny_ntu-late_240p"

dataset:
  root: "/home/archy1/datasets/fall-detection/ntu/processed/"
  modality: "both"

transforms:
  image_size: [240, 426]

dataloader:
  batch_size: 96
  num_workers: 8

tags:
  - "cnn"
  - "late"
  - "ntu"