model:
  backbone: "swin_t"
  pretrained: true

optimizer:
  lr: 1.0e-4
  weight_decay: 1.0e-2

train:
  epochs: 5
  output_dir: "weights/"
  run_name: "swin-t_ntu-early_240p"

dataset:
  root: "/home/archy1/datasets/fall-detection/ntu/processed/"
  modality: "both"

transforms:
  image_size: [240, 426]

dataloader:
  batch_size: 80 
  num_workers: 8

tags:
  - "swin"
  - "early"
  - "ntu"