fusion: "late"

model:
  backbone: "swin_t"
  rgb_weights: "weights/vit-b-16_ntu-rgb_240p/best.pt"
  depth_weights: "weights/vit-b-16_ntu-depth_240p/best.pt"

optimizer:
  lr: 1.0e-4
  weight_decay: 1.0e-2

train:
  epochs: 5
  output_dir: "weights/"
  run_name: "vit-b-16_ntu-late_240p"

dataset:
  root: "/home/tdutton/datasets/fall-detection/ntu/processed/"
  modality: "both"

transforms:
  image_size: [224, 224]

dataloader:
  batch_size: 128
  num_workers: 8

tags:
  - "vit"
  - "late"
  - "ntu"